#testing the issue-678 (9)
name: Build Project

on:
  push:
    branches: suyashgaonkar-issue678
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:
  test-docker:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Install JDK
        run: apt install openjdk-11-jdk
      - name: Execute Java
        run: |
          which java
          type java
          echo $JAVA_HOME
          echo $PATH
          java --help

  test-ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Install docker and docker-compose
        run: |
          apt -y update 
          apt -y install sudo curl
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh ./get-docker.sh
          apt-get install docker-compose-plugin
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Execute Java
        run: |
          which java
          type java
          echo $JAVA_HOME
          echo $PATH
          java --help