#testing the issue-678 (12)
name: Build Project

on:
  push:
    branches: suyashgaonkar-issue678
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:
  test-docker:
    runs-on: ubuntu-24.04
    container: docker:cli
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Install Java
        run: |
          apk update && \
          apk upgrade
          apk add openjdk11=11.0.24_p8-r0
      - name: Execute Java
        run: |
          which java
          type java
          echo "JAVA HOME "$JAVA_HOME
          # echo "JRE HOME "$JRE_HOME
          # export PATH=${JAVA_HOME}/bin/java
          echo "PATH "$PATH
          java -help
  test-ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Install docker and docker-compose
        run: |
          apt -y update 
          apt -y install sudo curl
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh ./get-docker.sh
          apt-get install docker-compose-plugin
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Execute Java
        run: |
          which java
          type java
          echo $JAVA_HOME
          echo $PATH
          java --help
  test-ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Execute Java
        run: |
          which java
          type java
          echo "JAVA HOME "$JAVA_HOME
          # echo "JRE HOME "$JRE_HOME
          # export PATH=${JAVA_HOME}/bin/java
          echo "PATH "$PATH
          java -help